events {}

http {
  upstream pushgateway {
    server pushgateway:9091;
  }

  server {
    listen 9091;

    location / {
      if ($http_authorization != "Bearer demo-sa-token-123") {
        return 401;
      }
      proxy_pass http://pushgateway;
    }
  }
}